services:
  ojs:
    build: .
    container_name: ojs-app
    restart: always
    ports:
      - "8081:80"
    # Removing restrictive environment section so Dokploy UI variables are inherited automatically
    volumes:
      - ojs_public:/var/www/html/public
      - ojs_private:/var/www/ojs-files

volumes:
  ojs_public:
  ojs_private:
